vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|05 Sep 1999 22:16:42 -0000
vti_author:SR|CSUWEB\\knape_jay
vti_modifiedby:SR|CSUWEB\\knape_jay
vti_nexttolasttimemodified:TW|05 Sep 1999 22:16:42 -0000
vti_timecreated:TR|16 Oct 2003 17:38:50 -0000
vti_cacheddtm:TX|16 Oct 2003 17:38:49 -0000
vti_filesize:IR|6723
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
vti_extenderversion:SR|5.0.2.2623
vti_lineageid:SR|{D9AEE1D5-42CF-4464-9CB5-F979D6817CCB}
vti_backlinkinfo:VX|
