vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|05 Sep 1999 22:16:56 -0000
vti_author:SR|CSUWEB\\knape_jay
vti_modifiedby:SR|CSUWEB\\knape_jay
vti_nexttolasttimemodified:TW|05 Sep 1999 22:16:56 -0000
vti_timecreated:TR|16 Oct 2003 17:32:46 -0000
vti_cacheddtm:TX|16 Oct 2003 17:32:45 -0000
vti_filesize:IR|12259
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
vti_extenderversion:SR|5.0.2.2623
vti_lineageid:SR|{AA729C9E-0D60-4541-8C9A-29A0A39F1424}
vti_backlinkinfo:VX|
