vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|05 Sep 1999 22:17:16 -0000
vti_author:SR|CSUWEB\\knape_jay
vti_modifiedby:SR|CSUWEB\\knape_jay
vti_nexttolasttimemodified:TW|05 Sep 1999 22:17:16 -0000
vti_timecreated:TR|16 Oct 2003 17:31:33 -0000
vti_cacheddtm:TX|16 Oct 2003 17:31:32 -0000
vti_filesize:IR|5438
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
vti_extenderversion:SR|5.0.2.2623
vti_lineageid:SR|{6DE0017B-E555-43B8-9080-FDEF035ADAE3}
vti_backlinkinfo:VX|
