vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|05 Sep 1999 22:17:29 -0000
vti_author:SR|CSUWEB\\knape_jay
vti_modifiedby:SR|CSUWEB\\knape_jay
vti_nexttolasttimemodified:TW|05 Sep 1999 22:17:29 -0000
vti_timecreated:TR|16 Oct 2003 17:34:33 -0000
vti_cacheddtm:TX|16 Oct 2003 17:34:32 -0000
vti_filesize:IR|11391
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
vti_extenderversion:SR|5.0.2.2623
vti_lineageid:SR|{8D542E5C-CA54-487E-A4A2-60D1A07DABAE}
vti_backlinkinfo:VX|
