vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|05 Sep 1999 22:18:31 -0000
vti_author:SR|CSUWEB\\knape_jay
vti_modifiedby:SR|CSUWEB\\knape_jay
vti_nexttolasttimemodified:TW|05 Sep 1999 22:18:31 -0000
vti_timecreated:TR|16 Oct 2003 17:36:20 -0000
vti_cacheddtm:TX|16 Oct 2003 17:36:19 -0000
vti_filesize:IR|26842
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
vti_extenderversion:SR|5.0.2.2623
vti_lineageid:SR|{2EC57BCD-99C0-4C15-99C5-99A2002BD64D}
vti_backlinkinfo:VX|
