vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|05 Sep 1999 22:19:03 -0000
vti_author:SR|CSUWEB\\knape_jay
vti_modifiedby:SR|CSUWEB\\knape_jay
vti_nexttolasttimemodified:TW|05 Sep 1999 22:19:03 -0000
vti_timecreated:TR|16 Oct 2003 17:35:47 -0000
vti_cacheddtm:TX|16 Oct 2003 17:35:47 -0000
vti_filesize:IR|11644
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
vti_extenderversion:SR|5.0.2.2623
vti_lineageid:SR|{DAF8A690-B2EC-48EF-8CA3-1ED0B5BB5E59}
vti_backlinkinfo:VX|
