vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|05 Sep 1999 22:19:32 -0000
vti_author:SR|CSUWEB\\knape_jay
vti_modifiedby:SR|CSUWEB\\knape_jay
vti_nexttolasttimemodified:TW|05 Sep 1999 22:19:32 -0000
vti_timecreated:TR|16 Oct 2003 17:38:03 -0000
vti_cacheddtm:TX|16 Oct 2003 17:38:03 -0000
vti_filesize:IR|8954
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
vti_extenderversion:SR|5.0.2.2623
vti_lineageid:SR|{BE48F740-DB2A-4B69-A931-0BF0E3F35F60}
vti_backlinkinfo:VX|
