vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|03 Jul 2002 17:05:47 -0000
vti_author:SR|CSUWEB\\knape_jay
vti_modifiedby:SR|CSUWEB\\knape_jay
vti_nexttolasttimemodified:TW|03 Jul 2002 17:05:47 -0000
vti_timecreated:TR|16 Oct 2003 17:32:24 -0000
vti_cacheddtm:TX|16 Oct 2003 17:32:24 -0000
vti_filesize:IR|12607
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
vti_extenderversion:SR|5.0.2.2623
vti_lineageid:SR|{D9A9B557-F0BC-43D2-ACF1-FF45A268C358}
vti_backlinkinfo:VX|
