vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|03 Jul 2002 17:05:48 -0000
vti_author:SR|CSUWEB\\knape_jay
vti_modifiedby:SR|CSUWEB\\knape_jay
vti_nexttolasttimemodified:TW|03 Jul 2002 17:05:48 -0000
vti_timecreated:TR|16 Oct 2003 17:35:29 -0000
vti_lineageid:SR|{7451FDB9-4369-4F82-BCC9-D3DEFBA4534F}
vti_cacheddtm:TX|16 Oct 2003 17:35:29 -0000
vti_filesize:IR|6581
vti_extenderversion:SR|5.0.2.2623
vti_backlinkinfo:VX|
