vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|03 Jul 2002 17:05:47 -0000
vti_author:SR|CSUWEB\\knape_jay
vti_modifiedby:SR|CSUWEB\\knape_jay
vti_nexttolasttimemodified:TW|03 Jul 2002 17:05:47 -0000
vti_timecreated:TR|16 Oct 2003 17:31:50 -0000
vti_cacheddtm:TX|16 Oct 2003 17:31:49 -0000
vti_filesize:IR|26842
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
vti_extenderversion:SR|5.0.2.2623
vti_lineageid:SR|{3D9993BF-F06C-45AE-B679-9F5AC3E65C57}
vti_backlinkinfo:VX|
