vti_encoding:SR|utf8-nl
vti_timelastmodified:TW|03 Jul 2002 17:05:49 -0000
vti_author:SR|CSUWEB\\knape_jay
vti_modifiedby:SR|CSUWEB\\knape_jay
vti_nexttolasttimemodified:TW|03 Jul 2002 17:05:49 -0000
vti_timecreated:TR|16 Oct 2003 17:34:17 -0000
vti_lineageid:SR|{A622C152-0A13-4FA3-925C-F00C0B2E868F}
vti_cacheddtm:TX|16 Oct 2003 17:34:17 -0000
vti_filesize:IR|12224
vti_extenderversion:SR|5.0.2.2623
vti_backlinkinfo:VX|
